# Generated by Django 3.0.8 on 2020-08-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200731_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='comment',
            new_name='description',
        ),
    ]
