# Generated by Django 3.0.8 on 2020-08-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200803_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
    ]
