# Generated by Django 3.0.8 on 2020-08-09 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('theme', 'THEME'), ('harmony', 'HARMONY'), ('song', 'SONG'), ('other', 'OTHER')], default='other', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Category'),
        ),
    ]
