# Generated by Django 3.0.8 on 2020-08-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_video_is_fav'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_fav',
            new_name='favorite',
        ),
    ]
