# Generated by Django 3.0.8 on 2020-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200809_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='display_name',
            field=models.CharField(blank=True, default='name', max_length=255),
        ),
    ]
