# Generated by Django 3.0.8 on 2020-08-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20200809_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
