# Generated by Django 3.1 on 2020-08-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, height_field=480, upload_to='static/images/', width_field=640),
        ),
    ]
